### PR TITLE
Persist WSL_INTEROP in child environment, for WSL2

### PR DESCRIPTION
**Pull request by dtmdl**
With this patch wsl-sudo.py works for me in WSL2.

### CODE REVIEW

**Comment by Chronial** [comment]
Does this actually get you an elevated shell or just a working shell?

**Comment by dtmdl** [comment]
Yes, it gets you a  working, elevated shell:

image

**Comment by Growiel** [comment]
I confirm that this works for me too ! WSL2 and the elevated powershell command worked flawlessly.

A merge would be appreciated.

**Comment by pmorch** [comment]
I can also confirm that this works for WSL2 and fixes #1.

**Comment by Chronial** [comment]
Thanks a lot for the patch and sorry for the slow merge.

**Pull request merged**
